language: ruby
rvm:
  - 2.3.3
sudo: required

script:
  - echo $TRAVIS_BRANCH
  
before_install:
 - gem update --system

branches:
  only:
    - /^dev.*$/
    - topic-add-deployflow

after_success:
- sudo pip install awscli
- sudo apt-get install jq
- mkdir -p /vat/tmp/release
- tar -zcf /var/tmp/release/kawabata.tar.gz --exclude ".git" ./
- if [ "$TRAVIS_BRANCH" =~ /^dev.*$/ ]; then DEV_DEPLOY_BRANCH="$TRAVIS_BRANCH" fi
- echo $DEV_DEPLOY_BRANCH

deploy:
- provider: script
  skip_cleanup: true
  script: sh deploy/deploy.sh
  on:
#   branch: $TRAVIS_BRANCH
   branch: $DEV_DEPLOY_BRANCH
#   condition: "$TRAVIS_BRANCH =~ /^dev.*$"
#   condition: $TRAVIS_BRANCH = develop

after_deploy:
- echo 'end deploy'







