language: ruby
rvm:
  - 2.3.3
#sudo: required

script:
  - echo $TRAVIS_BRANCH
  
before_install:
 - gem update --system

branches:
  only:
    - /^dev.*$/
    - /^dev-.*$/
    - topic-add-deployflow
    - /^travis-.*$/

after_success:
- sudo pip install awscli
- sudo apt-get install jq
- mkdir -p /var/tmp/release
- tar -zcf /var/tmp/release/kawabata.tar.gz --exclude ".git" ./;
- source deploy/set_branch.sh

deploy:
  provider: codedeploy
  access_key_id: $DEV_AWS_ACCESS_KEY_ID
  secret_access_key: $DEV_AWS_SECRET_ACCESS_KEY
  bucket: plussign
  key: code-test.zip
  application: codedeploy_test
  deployment_group: dev-deployment-group
  region: ap-northeast-1
  on:
    branch: $DEV_DEPLOY_BRANCH

after_deploy:
- echo 'end deploy'
- echo 'end deploy'







