language: ruby
rvm:
  - 2.3.3
#sudo: required

script:
  - echo $TRAVIS_BRANCH
  
before_install:
 - gem update --system

branches:
  only:
    - /^dev.*$/
    - /^dev-.*$/
    - topic-add-deployflow

after_success:
- sudo pip install awscli
- sudo apt-get install jq
- mkdir -p /var/tmp/release
- tar -zcf /var/tmp/release/kawabata.tar.gz --exclude ".git" ./;
- source deploy/set_branch.sh

deploy:
- provider: script
  skip_cleanup: true
  script: sh deploy/test1.sh
  on: &1
#   branch: $TRAVIS_BRANCH
   branch: $DEV_DEPLOY_BRANCH
- provider: script
  skip_cleanup: true
  script: sh deploy/test2.sh
  on: *1
- provider: script
  skip_cleanup: true
  script: sh deploy/test3.sh
  on: &1
   branch: $TEST_DEPLOY_BRANCH
- provider: script
  skip_cleanup: true
  script: sh deploy/test4.sh
  on: *1


after_deploy:
- echo 'end deploy'







